version: '3'

networks:
  hw4:
    driver: bridge

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9095:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://kafka-1:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 500
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_data/500:/kafka

  kafka-2:
    image: wurstmeister/kafka
    ports:
      - "9096:9094"
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://kafka-2:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 501
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_data/501:/kafka

  kafka-3:
    image: wurstmeister/kafka
    ports:
      - "9097:9094"
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://localhost:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 502
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_data/502:/kafka

  postgres-1:
    image: postgres:latest
    container_name: postgres_container_hw4_1
    environment:
      - POSTGRES_USER=${DB_USER_1}
      - POSTGRES_PASSWORD=${DB_PASSWORD_1}
      - POSTGRES_DB=${DB_NAME_1}
      - DATABASE_HOST=${DB_HOST_1}
    ports:
      - '${DB_HOST_1}:${DB_PORT_1}:5432'
    networks:
      - hw4
  postgres-1_even:
    image: postgres:latest
    container_name: postgres_container_hw4_1_even
    environment:
      - POSTGRES_USER=${DB_USER_1}
      - POSTGRES_PASSWORD=${DB_PASSWORD_1}
      - POSTGRES_DB=${DB_NAME_1}
      - DATABASE_HOST=${DB_HOST_1}
    networks:
      - hw4
    ports:
      - '${DB_HOST_1}:${DB_PORT_1_EVEN}:5432'
  postgres-1_odd:
    image: postgres:latest
    container_name: postgres_container_hw4_1_odd
    environment:
      - POSTGRES_USER=${DB_USER_1}
      - POSTGRES_PASSWORD=${DB_PASSWORD_1}
      - POSTGRES_DB=${DB_NAME_1}
      - DATABASE_HOST=${DB_HOST_1}
    networks:
      - hw4
    ports:
      - '${DB_HOST_1}:${DB_PORT_1_ODD}:5432'
  postgres-2:
    image: postgres:latest
    container_name: postgres_container_hw4_2
    environment:
      - POSTGRES_USER=${DB_USER_2}
      - POSTGRES_PASSWORD=${DB_PASSWORD_2}
      - POSTGRES_DB=${DB_NAME_2}
      - DATABASE_HOST=${DB_HOST_2}
    ports:
      - '${DB_HOST_2}:${DB_PORT_2}:5432'
    networks:
      - hw4

  postgres-3:
    image: postgres:latest
    container_name: postgres_container_hw4_3
    environment:
      - POSTGRES_USER=${DB_USER_3}
      - POSTGRES_PASSWORD=${DB_PASSWORD_3}
      - POSTGRES_DB=${DB_NAME_3}
      - DATABASE_HOST=${DB_HOST_3}
    ports:
      - '${DB_HOST_3}:${DB_PORT_3}:5432'
    networks:
      - hw4
  memcached:
    image: memcached:latest
    container_name: memcached_hw4
    ports:
      - '127.0.0.1:11211:11211'